### ISSUE TITLE
pakku can't resolve a dependancy in 'extra'

### ISSUE THREAD

**Issue by xxxxme** [zqqw/pakku#32]
`pakku -S keysmith-git`
complains, "error: unable to satisfy dependency 'frameworkintegration ' required by keysmith-git"
but this package is already installed from 'extra' and compiling it with makepkg (no changes to PKGBUILD) gives no errors.

Pakku v0.14-31-g334e09a
Pacman v6.0.2 - libalpm v13.0.2

**Comment by zqqw** [comment]
I think this is probably a problem in the keysmith-git PKGBUILD, from $ man PKGBUILD :        "depends (array)  An array of packages this package depends on to run. Entries in this list should be surrounded with single quotes"
But in keysmith-git they are double quotes. Quickly testing just now, when I replaced these with single quotes it started to build then failed later during the build process. I think you should put a comment on the keysmith-git AUR page and hopefully the maintainer will update it:
https://aur.archlinux.org/packages/keysmith-git

**Comment by zqqw** [comment]
https://github.com/zqqw/pakku/commit/a7a118833e6eda27beab753ec7dacfe73187ec9c
https://github.com/zqqw/pakku/commit/1276d35660b25cc5e6215b3509bf10c63675ad15
That should fix it. The hidden .SRCINFO file in the AUR repo for keysmith-git has been edited by hand and a stray whitespace character was left on the end of the line saying "frameworkintegration " which by chance didn't get removed by the initial file parsing in Pakku, although at some later points in the code it did. Also the way Pakku deleted files and quit immediately wasn't helpful to allow anyone to try and manually remedy the situation, I think this fix will be OK and still quit when needed, it's difficult when dealing with situations that shouldn't happen to decide exactly what should happen. The .SRCINFO file should really be corrected, but it will work in Pakku now regardless, matching how makepkg handled it. Thank you for highlighting this interesting bug.
