### ISSUE TITLE
Pakku may need to be updated to work with pacman 6.1

### ISSUE THREAD

**Issue by crushten** [zqqw/pakku#33]
Seems like the pacman 6.1 upgrade added new libalpm libraries.

Getting a `pakku: error while loading shared libraries: libalpm.so.13: cannot open shared object file: No such file or directory` when trying to run `pakku -Syu`.

It is similar to this https://github.com/Morganamilo/paru/issues/1149.

Let me know if anything else is needed to help with this.

**Comment by zqqw** [comment]
Just rebuild pakku, it will link to the new libs and work again. Thank you for the notification.
Use makepkg and then install with pacman -U, I put a note on the AUR page too.

**Comment by crushten** [comment]
Ah lol didnt think about that. Thanks!

I will close this since rebuild works fine.
