### ISSUE TITLE
Update needed due to pacman 14

### ISSUE THREAD

**Issue by medicamin** [zqqw/pakku#34]
Hi there,
I'm using pakku as AUR helper. it's simple and lightweight. According to the latest pacman update to version 14, pakku needs to be updated to use libalpm.so.14. otherwise it doesn't work:
```pakku error while loading shared libraries: libalpm.so.13: cannot open shared object file: No such file or directory```

Thanks a lot.

**Comment by zqqw** [comment]
Just rebuild and it should be fine - this same point was raised here:
https://github.com/zqqw/pakku/issues/33
but as the issue was closed yesterday you must have missed it, easily done! Hope that fixes it for you, best wishes.

**Comment by medicamin** [comment]
Thank you, and sorry for dublicate.
